import nest
import matplotlib.pylab as plt

nest.Install("extracerebmodule")

n = 300  # Number of MFs
trial_len = 300  # [ms]
n_trial = 20  # Number of trials
target = 0.0  # [deg] final position of J1
prism = 0.0  # [deg] deviation generated by the prism

planner = nest.Create(
        "planner_neuron",
        n=n,
        params={
            "trial_length": trial_len,
            "target": target,
            "prism_deviation": prism,
            "gain_rate": 10.0,
            }
        )

cortex = nest.Create(
        "cortex_neuron",
        n=n,
        params={
            "trial_length": trial_len,
            "fibers_per_joint": n//4,
            "rbf_sdev": 15.0,
            }
        )

for i, neuron in enumerate(cortex):
    nest.SetStatus([neuron], {"joint_id": i // (n//4),
                              "fiber_id": i % (n//4)})

nest.Connect(planner, cortex, 'one_to_one')

planner_sd = nest.Create("spike_detector")
nest.Connect(planner, planner_sd)

ctx_sd = nest.Create("spike_detector")
nest.Connect(cortex, ctx_sd)

for trial in range(n_trial):
    nest.Simulate(trial_len)

    simtime = (trial + 1) * trial_len
    n_events = nest.GetStatus(planner_sd, keys="n_events")[0]
    rate = n_events / simtime * 1e3 / n
    print("Planner rate:", rate)

fig, axs = plt.subplots(2)

dSD = nest.GetStatus(ctx_sd, keys="events")[0]
evs = dSD["senders"]
ts = dSD["times"]

axs[0].scatter(ts, evs, marker='.')

dSD = nest.GetStatus(planner_sd, keys="events")[0]
evs = dSD["senders"]
ts = dSD["times"]

axs[1].scatter(ts, evs, marker='.')

plt.show()
