import nest
import matplotlib.pylab as plt

nest.Install("extracerebmodule")

n = 300  # Number of MFs
trial_len = 300  # [ms]
n_trial = 20  # Number of trials
target = 0.0  # [deg] final position of J1
prism = 0.0  # [deg] deviation generated by the prism

planner = nest.Create(
        "planner_neuron",
        n=n,
        params={
            "trial_length": trial_len,
            "target": target,
            "prism_deviation": prism,
            "gain_rate": 10.0,
            }
        )

cortex = nest.Create(
        "cortex_neuron",
        n=n,
        params={
            "trial_length": trial_len,
            "fibers_per_joint": n//4,
            "rbf_sdev": 15.0,
            }
        )

for i, neuron in enumerate(cortex):
    nest.SetStatus([neuron], {"joint_id": i // (n//4),
                              "fiber_id": i % (n//4)})

nest.Connect(planner, cortex, 'one_to_one')

spikedetector = nest.Create("spike_detector")
nest.Connect(cortex, spikedetector)

for trial in range(n_trial):
    nest.Simulate(trial_len)

dSD = nest.GetStatus(spikedetector, keys="events")[0]
evs = dSD["senders"]
ts = dSD["times"]

plt.scatter(ts, evs, marker='.')
plt.show()
